---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: invoices-svc
  name: invoices-svc
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      run: invoices-svc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: invoices-svc
    spec:
      containers:
      - image: invoices_svc:v1
        imagePullPolicy: IfNotPresent
        name: invoices-svc
        ports:
        - containerPort: 8080
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: invoices-svc
  name: invoices-svc
  namespace: default
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  fws-invoices_mapping
      prefix: /invoices/
      rewrite: /api/invoices/
      service: invoices-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: invoices-svc
  sessionAffinity: None
  type: ClusterIP